import { IWorkShop } from "./types";

export const workshopsMockData: Record<string, IWorkShop[]> = {
  day1: [
    {
      date: "5 Jan 2026",
      time: "4:00PM - 5:00PM",
      imageAlt: "Metacamp",
      imageSrc: "/workshops/Metacamp2.png",
      // secondImageSrc: "/workshops/EmbeddedLLM.svg",
      title: "Build Everything Onchain: Migrating Web2 Apps to Fully Onchain Systems",
      company: "Metacamp",
      description: "Curious about how Web2 apps can go fully onchain? This session dives into the design mindset, tooling, and real considerations behind building truly onchain systems — perfect for builders looking to push beyond smart contracts.",
      registrationLink: "https://forms.gle/3c4dt9dYGcrD4v4a6",
      speakers: ["Jonas Chen, Co-Founder"],
      disabled: false,
    },
  ],
  day2: [
    {
      date: "6 Jan 2026",
      time: "10:00AM - 11.00AM",
      imageAlt: "GSR",
      imageSrc: "/workshops/GSR.jpg",
      title: "Stable coin and DeFi",
      company: "GSR",
      description: "Whether you’re new to DeFi or exploring a career in crypto, this session offers both technical insights and industry perspectives.",
      registrationLink: "https://forms.gle/3c4dt9dYGcrD4v4a6",
      speakers: ["Aravind Srinivasan, Head of Systematic OTC Trading (Crypto/FX)", "Ray Pan, Senior Software Engineer (DeFi-focused)"],
      disabled: false,
    },
    {
      date: "6 Jan 2026",
      time: "12:00PM - 12:30PM",
      imageAlt: "animoca",
      imageSrc: "/workshops/animoca.png",
      title: "Intro to RWA & Tokenization",
      company: "Animoca Brands",
      description: "If you’re curious about how real-world assets are being brought onchain and why tokenization matters, this session is a great starting point.",
      registrationLink: "https://forms.gle/3c4dt9dYGcrD4v4a6",
      speakers: ["Caleb Lim, Associate Director"],
      disabled: false,
    },
    {
      date: "6 Jan 2026",
      time: "5:00PM - 6:00PM",
      imageAlt: "Ripple",
      imageSrc: "/workshops/Ripple.png",
      title: "XRPL, Developer Tools, Hackathon Resources & Problem Statement",
      company: "Ripple",
      description: "If you’re considering building on XRPL or want to explore Ripple’s problem statement for the hackathon, this is a must-attend.",
      registrationLink: "https://forms.gle/3c4dt9dYGcrD4v4a6",
      speakers: ["Maxime Dienger, Dev Advocate", "Emma Nasseri, University Blockchain Research PM"],
      disabled: false,
    },
  ],
};
